name: corebird-diddledan
version: "1.3.3"
summary: CoreBird Twitter Client
description: |
  Corebird is a modern and lightweight Twitter client for the GNOME 3 desktop. It
  features inline image and video preview, creation of lists and favorites,
  filtering of tweets and full text search. Corebird is able to manage multiple
  Twitter accounts.
confinement: strict
slots:
  dbus-corebird:
    interface: dbus
    bus: session
    name: org.baedert.corebird
architectures: [ amd64, i386 ]
apps:
  corebird:
    command: desktop-launch $SNAP/usr/bin/corebird
    plugs: [gsettings, home, network, pulseaudio, unity7]
parts:
  corebird:
    source: https://github.com/baedert/corebird/releases/download/1.3.3/corebird-1.3.3.tar.xz
    plugin: autotools
    configflags: [ '--prefix=/usr', '--disable-spellcheck' ]
    build-packages:
      - gettext
      - gstreamer1.0-alsa
      - gstreamer1.0-fluendo-mp3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-tools
      - gstreamer1.0-x
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer1.0-dev
      - libjson-glib-dev
      - librest-dev
      - libsqlite3-dev
      - libxml2-utils
      - valac
    stage-packages:
      - gstreamer1.0-alsa
      - gstreamer1.0-fluendo-mp3
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-tools
      - gstreamer1.0-x
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer-plugins-bad1.0-0
      - libjson-glib-1.0-0
      - librest-0.7-0
      - libsqlite3-0
      - libxml2
      - zlib1g
    after: [ desktop-gtk3 ]
