name: corebird
version: "1.3.1"
summary: CoreBird Twitter Client
description: |
  Corebird is a modern and lightweight Twitter client for the GNOME 3 desktop. It
  features inline image and video preview, creation of lists and favorites,
  filtering of tweets and full text search. Corebird is able to manage multiple
  Twitter accounts.
confinement: strict
apps:
  corebird:
    command: desktop-launch $SNAP/usr/bin/corebird
    plugs: [unity7, gsettings, pulseaudio, network]
parts:
  corebird:
    source: https://github.com/baedert/corebird/releases/download/1.3.1/corebird-1.3.1.tar.xz
    plugin: autotools
    configflags: [ '--prefix=/usr' ]
    build-packages:
      - gettext
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libjson-glib-dev
      - librest-dev
      - libsqlite3-dev
      - libxml2-utils
      - valac
    stage-packages:
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-libav
    after: [ desktop-gtk3 ]