name: corebird
version: "1.5.1"
grade: stable
summary: CoreBird Twitter Client
description: |
  Corebird is a modern and lightweight Twitter client for the GNOME 3 desktop. It
  features inline image and video preview, creation of lists and favorites,
  filtering of tweets and full text search. Corebird is able to manage multiple
  Twitter accounts.
icon: corebird.svg
confinement: strict
slots:
  dbus-corebird:
    interface: dbus
    bus: session
    name: org.baedert.corebird
apps:
  corebird:
    command: desktop-launch $SNAP/usr/bin/corebird
    #desktop: meta/gui/corebird.desktop
    #desktop: usr/share/applications/org.baedert.corebird.desktop
    plugs:
      - gsettings
      - home
      - network
      - network-observe
      - opengl
      - pulseaudio
      - unity7
      - x11
parts:
  desktop-helper:
    plugin: make
    source: desktop-helpers
    source-subdir: gtk
    make-parameters: ["FLAVOR=gtk3"]
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - shared-mime-info
      - locales-all

  openh264:
    plugin: make
    source: https://github.com/cisco/openh264/archive/v1.6.0.tar.gz
    build-packages:
      - nasm
    stage-packages:
      - bzip2
      - curl
    prime:
      - '-bin/bz*'
      - '-usr/local'

  corebird:
    plugin: jhbuild
    module-set: corebird.modules
    module-set-dir: .
    modules:
      - corebird
    cflags: '-Os'
    build-packages:
      - bzip2
      - desktop-file-utils
      - doxygen
      - libcairo2-dev
      - libcurl4-openssl-dev
      - libdbus-1-dev
      - libegl1-mesa-dev
      - libenchant-dev
      - libepoxy-dev
      - libfaad-dev
      - libffi-dev
      - libfontconfig1-dev
      - libgl1-mesa-dev
      - libgnutls-dev
      - libgudev-1.0-dev
      - libmount-dev
      - liborc-0.4-dev
      - libpng12-dev
      - libproxy-dev
      - libpulse-dev
      - libsqlite3-dev
      - libtiff5-dev
      - libunwind-dev
      - libv4l-dev
      - libwayland-dev
      - libxcb-xkb-dev
      - libxft-dev
      - libxi-dev
      - libxml2-utils
      - libxslt1-dev
      - libxtst-dev
      - nasm
      - ragel
      - tar
      - wget
      - xmlto
      - xutils-dev
      - xz-utils
      - yasm
      - valac
    stage-packages:
      - bzip2
      - curl
      - libfontconfig1
    after: [desktop-helper, openh264]
    prime:
      - '-usr/share/aclocal'
      - '-bash-completion'
      - '-etc/gss/'
      - '-etc/ldap/'
      - '-defaults'
      - '-devhelp'
      - '-usr/_jhbuild'
      - '-usr/bin/*gettext*'
      - '-usr/bin/autopoint'
      - '-usr/bin/broadwayd'
      - '-usr/bin/croco-*'
      - '-usr/bin/csslint*'
      - '-usr/bin/envsubst'
      - '-usr/bin/gapplication'
      - '-usr/bin/gdbus*'
      - '-usr/bin/gdk-pixbuf-csource'
      - '-usr/bin/gdk-pixbuf-pixdata'
      - '-usr/bin/gdk-pixbuf-thumbnailer'
      - '-usr/bin/g-ir-*'
      - '-usr/bin/glib-*'
      - '-usr/bin/gobject-*'
      - '-usr/bin/gresource'
      - '-usr/bin/gsettings'
      - '-usr/bin/gst*'
      - '-usr/bin/gtester*'
      - '-usr/bin/gtk*'
      - '-usr/bin/hb-*'
      - '-usr/bin/json-glib-*'
      - '-usr/bin/lcf'
      - '-usr/bin/meson*'
      - '-usr/bin/msg*'
      - '-usr/bin/pango*'
      - '-usr/bin/recode*'
      - '-usr/bin/rsvg*'
      - '-usr/bin/ucf*'
      - '-usr/bin/vala*'
      - '-usr/bin/vapi*'
      - '-usr/bin/yelp*'
      - '-usr/etc'
      - '-usr/include'
      - '-usr/lib/*sasl*'
      - '-usr/lib/cmake'
      - '-usr/lib/gcc'
      - '-usr/lib/gtk-2.0'
      - '-usr/lib/pkgconfig'
      - '-usr/lib/python*'
      - '-usr/lib/systemd'
      - '-usr/lib/vala*'
      - '-usr/libexec/at-spi*'
      - '-usr/libexec/glib-pacrunner'
      - '-usr/libexec/installed-tests'
      - '-usr/share/applications/gtk-*'
      - '-usr/share/bash-completion'
      - '-usr/share/devhelp'
      - '-usr/share/doc*'
      - '-usr/share/gdb'
      - '-usr/share/gettext*'
      - '-usr/share/gir-1.0'
      - '-usr/share/glib-2.0/codegen'
      - '-usr/share/glib-2.0/gdb'
      - '-usr/share/glib-2.0/gettext'
      - '-usr/share/glib-2.0/valgrind'
      - '-usr/share/gobject-introspection-1.0'
      - '-usr/share/gst-plugins-base'
      - '-usr/share/gstreamer-1.0'
      - '-usr/share/gtk-3.0'
      - '-usr/share/gtk-doc'
      - '-usr/share/help'
      - '-usr/share/info'
      - '-usr/share/installed-tests'
      - '-usr/share/lintian'
      - '-usr/share/locale/**/gdk-pixbuf*'
      - '-usr/share/locale/**/gettext*'
      - '-usr/share/locale/**/glib*'
      - '-usr/share/locale/**/gsettings-desktop-schemas*'
      - '-usr/share/locale/**/gst-plugins-*'
      - '-usr/share/locale/**/gstreamer-1.0*'
      - '-usr/share/locale/**/gtk30*'
      - '-usr/share/locale/**/iso_*'
      - '-usr/share/locale/**/json-glib*'
      - '-usr/share/locale/**/libsoup*'
      - '-usr/share/man'
      - '-usr/share/pkgconfig'
      - '-usr/share/sgml'
      - '-usr/share/thumbnailers'
      - '-usr/share/vala*'
      - '-usr/share/yelp*'
      - '-usr/share/zsh'
