name: corebird
version: "1.6.0"
grade: stable
summary: CoreBird Twitter Client
description: |
  Corebird is a modern and lightweight Twitter client for the GNOME 3 desktop. It
  features inline image and video preview, creation of lists and favorites,
  filtering of tweets and full text search. Corebird is able to manage multiple
  Twitter accounts.
icon: data/corebird.svg

grade: stable
confinement: strict

slots:
  dbus-corebird:
    interface: dbus
    bus: session
    name: org.baedert.corebird

plugs:
  gnome-3-24-platform:
    interface: content
    target: gnome-platform
    default-provider: gnome-3-24:gnome-3-24-platform

apps:
  corebird:
    command: |
      desktop-launch pulse-launch libopenh264-launch gstreamer-launch $SNAP/usr/bin/corebird
    plugs:
      - gnome-3-24-platform
      - gsettings
      - home
      - network
      - opengl
      - pulseaudio
      - unity7
      - x11

parts:
  gnome-platform:
    plugin: nil
    prepare: |
      echo "deb http://ppa.launchpad.net/ubuntu-desktop/gnome-3-24/ubuntu xenial main" | tee /etc/apt/sources.list.d/gnome-3-24.list
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 399B698EEA9EF163B6F9A0F62CC98497A1231595
      apt update
      apt upgrade -yy
    prime:
      - -*

  gstreamer-launch:
    plugin: dump
    source: snap-files
    prepare: |
      chmod +x gstreamer-launch
      chmod +x pulse-launch
    organize:
      gstreamer-launch: bin/gstreamer-launch
      pulse-launch: bin/pulse-launch
    prime:
      - bin/gstreamer-launch
      - bin/pulse-launch
    build-attributes: [no-system-libraries]

  libopenh264-helper:
    source: libopenh264-helper
    source-subdir: libopenh264
    plugin: make
    stage-packages:
      - bzip2
      - curl
    prime:
      - bin/bunzip2
      - bin/libopenh264-launch
      - usr/bin/curl
      - usr/lib/**/libasn1*
      - usr/lib/**/libcurl-gnutls*
      - usr/lib/**/libgssapi.so*
      - usr/lib/**/libhcrypto*
      - usr/lib/**/libheimbase*
      - usr/lib/**/libheimntlm*
      - usr/lib/**/libhx509*
      - usr/lib/**/liblber*
      - usr/lib/**/libldap*
      - usr/lib/**/libroken*
      - usr/lib/**/librtmp*
      - usr/lib/**/libsasl2*
      - usr/lib/**/libwind*
      - usr/lib/**/sasl2
    build-attributes: [no-system-libraries]

  libopenh264-library:
    plugin: make
    source: https://github.com/cisco/openh264/archive/v1.7.0.tar.gz
    build-packages:
      - g++
      - libasound2-dev
      - libpulse-dev
      - nasm
    stage-packages: [libpulse0]
    prime:
      - lib/libjson-c*
      - lib/libwrap*
      - usr/lib/**/libasyncns*
      - usr/lib/**/libFLAC*
      - usr/lib/**/libpulse*
      - usr/lib/**/libsndfile*
      - usr/lib/**/libvorbisenc*
      - usr/lib/**/pulseaudio
      - usr/local/lib/libopenh264.so*
    build-attributes: [no-system-libraries]

  gstreamer:
    plugin: autotools
    source: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.12.2.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-benchmarks
      - --disable-check
      - --disable-debug
      - --disable-examples
      - --disable-gst-debug
      - --disable-gst-tracer-hooks
      - --disable-rpath
      - --disable-tests
      - --disable-tools
    build-packages:
      - bison
      - flex
      - libasound2-dev
      - liborc-0.4-dev
      - libpulse-dev
      - libxv-dev
    stage-packages:
      - libpulse0
      - libxv1
    after: [libopenh264-library, gnome-platform]
    prime:
      - lib/libjson-c*
      - usr/lib/**/libXv.so*
      - usr/lib/gstreamer-1.0
      - -usr/lib/gstreamer-1.0/include
      - usr/lib/libgst*
      - usr/libexec/gstreamer-1.0/gst-plugin-scanner
      - usr/share/locale/**/gstreamer*
    build-attributes: [no-system-libraries]

  # gstreamer-vaapi:
  #   plugin: autotools
  #   source: https://gstreamer.freedesktop.org/src/gstreamer-vaapi/gstreamer-vaapi-1.12.2.tar.xz
  #   configflags:
  #     - --prefix=/usr
  #   build-packages:
  #     - libgles2-mesa-dev
  #     - libv4l-dev
  #     - libva-dev
  #     - libwayland-dev
  #     - libxrandr-dev
  #   stage-packages:
  #     - libv4l-0
  #     - libva-wayland1
  #     - libva-x11-1
  #     - libva1
  #   after:
  #     - gnome-platform
  #     - gst-plugins-bad
  #     - gst-plugins-base
  #     - gstreamer
  #   prime:
  #     - usr/lib/gstreamer-1.0
  #     - usr/lib/libgst*
  #     - usr/lib/**/libboost*
  #     - usr/lib/**/libcapnp*
  #     - usr/lib/**/libv4l*
  #     - usr/lib/**/libva*
  #     - usr/share/locale/*

  gst-plugins-base:
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.12.2.tar.xz
    configflags:
      - --prefix=/usr
    build-packages: [libasound2-dev, libcairo2-dev, libpulse-dev]
    stage-packages: [libpulse0]
    after: [gstreamer, gnome-platform]
    prime:
      - lib/libjson-c*
      - usr/lib/gstreamer-1.0
      - -usr/lib/gstreamer-1.0/include
      - usr/lib/libgst*
      - usr/share/locale/**/gst-plugins-base*
    build-attributes: [no-system-libraries]

  gst-plugins-libav:
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.12.2.tar.xz
    configflags:
      - --enable-gpl
      - --enable-orc
      - --prefix=/usr
      - --with-libav-extra-configure="--disable-everything\ --enable-avcodec\ --enable-avformat\ --enable-decoder=aac,h264,h264_crystalhd,h264_cuvid,h264_mediacodec,h264_mmal,h264_qsv,h264_vda,h264_vdpau,mpeg4,mpeg4_crystalhd,mpeg4_cuvid,mpeg4_mediacodec,mpeg4_mmal,mpeg4_vdpau\ --enable-gnutls\ --enable-opengl\ --enable-outdev=opengl,pulse,xv\ --enable-parser=aac,h264,mpeg4video\ --enable-pic\ --enable-protocols=cache,data,file,hls,http,httpproxy,https,pipe,tls_gnutls,unix"
      - --with-pkg-config-path="$SNAPCRAFT_STAGE/usr/local/lib/pkgconfig:$SNAPCRAFT_STAGE/usr/lib/pkgconfig:$SNAPCRAFT_STAGE/usr/lib/$(gcc --print-multiarch)/pkgconfig"
    build-packages:
      - bison
      - flex
      - libasound2-dev
      - libgnutls28-dev
      - liborc-0.4-dev
      - libpulse-dev
      - libva-dev
      - libwayland-dev
      - libxrandr-dev
      - yasm
      - zlib1g-dev
    stage-packages:
      - libpulse0
      - libva-wayland1
      - libva-x11-1
      - libva1
      - zlib1g
    after: [gst-plugins-base, libopenh264-library, gnome-platform]
    prime:
      - lib/libjson-c*
      - usr/lib/gstreamer-1.0
      - -usr/lib/gstreamer-1.0/include
      - usr/lib/libgst*
      - usr/lib/**/libva*
      - usr/share/locale/**/gst-plugins-libav*
    build-attributes: [no-system-libraries]

  gst-plugins-good:
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.12.2.tar.xz
    configflags:
      - --prefix=/usr
      - --disable-aalib
      - --disable-aalibtest
      - --disable-alpha
      - --disable-apetag
      - --disable-audiofx
      - --disable-cutter
      - --disable-debug
      - --disable-debugutils
      - --disable-directsound
      - --disable-dtmf
      - --disable-dv1394
      - --disable-effectv
      - --disable-equalizer
      - --disable-examples
      - --disable-flac
      - --disable-flv
      - --disable-flx
      - --disable-goom
      - --disable-goom2k1
      - --disable-icydemux
      - --disable-id3demux
      - --disable-imagefreeze
      - --disable-interleave
      - --disable-jack
      - --disable-jpeg
      - --disable-law
      - --disable-level
      - --disable-libcaca
      - --disable-libdv
      - --disable-libpng
      - --disable-monoscope
      - --disable-oss
      - --disable-oss4
      - --disable-osx_audio
      - --disable-osx_video
      - --disable-replaygain
      - --disable-rpath
      - --disable-rtp
      - --disable-rtpmanager
      - --disable-rtsp
      - --disable-shapewipe
      - --disable-shout2
      - --disable-smpte
      - --disable-spectrum
      - --disable-speex
      - --disable-sunaudio
      - --disable-taglib
      - --disable-udp
      - --disable-videobox
      - --disable-vpx
      - --disable-waveform
      - --disable-wavenc
      - --disable-wavpack
      - --disable-wavparse
      - --disable-y4m
    build-packages:
      - bison
      - flex
      - libasound2-dev
      - liborc-0.4-dev
      - libpulse-dev
    stage-packages:
      - libpulse0
    after:
      - gnome-platform
      - gst-plugins-base
      - gstreamer
      - libopenh264-library
    prime:
      - lib/libjson-c*
      - usr/lib/gstreamer-1.0
      - -usr/lib/gstreamer-1.0/include
      - usr/lib/libgst*
      - usr/share/locale/**/gst-plugins-good*
    build-attributes: [no-system-libraries]

  gst-plugins-bad:
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.12.2.tar.xz
    configflags:
      - --prefix=/usr
      - --with-pkg-config-path="$SNAPCRAFT_STAGE/usr/local/lib/pkgconfig:$SNAPCRAFT_STAGE/usr/lib/pkgconfig:$SNAPCRAFT_STAGE/usr/lib/$(gcc --print-multiarch)/pkgconfig"
      - --disable-accurip
      - --disable-acm
      - --disable-adpcmdec
      - --disable-adpcmenc
      - --disable-aiff
      - --disable-android_media
      - --disable-apexsink
      - --disable-apple_media
      - --disable-asfmux
      - --disable-assrender
      - --disable-audiofxbad
      - --disable-audiomixer
      - --disable-audiovisualizers
      - --disable-autoconvert
      - --disable-bayer
      - --disable-bluez
      - --disable-bs2b
      - --disable-bz2
      - --disable-camerabin2
      - --disable-cdxaparse
      - --disable-chromaprint
      - --disable-coloreffects
      - --disable-compositor
      - --disable-daala
      - --disable-dash
      - --disable-dc1394
      - --disable-dccp
      - --disable-debug
      - --disable-debugutils
      - --disable-decklink
      - --disable-direct3d
      - --disable-directfb
      - --disable-directsound
      - --disable-dtls
      - --disable-dvb
      - --disable-dvbsuboverlay
      - --disable-dvdspu
      - --disable-examples
      - --disable-faac
      - --disable-faceoverlay
      - --disable-fbdev
      - --disable-fdk_aac
      - --disable-festival
      - --disable-fieldanalysis
      - --disable-flite
      - --disable-fluidsynth
      - --disable-freeverb
      - --disable-frei0r
      - --disable-gaudieffects
      - --disable-gdp
      - --disable-geometrictransform
      - --disable-gme
      - --disable-gsm
      - --disable-hdvparse
      - --disable-id3tag
      - --disable-inter
      - --disable-interlace
      - --disable-ivfparse
      - --disable-ivtc
      - --disable-jp2kdecimator
      - --disable-jpegformat
      - --disable-kate
      - --disable-kms
      - --disable-ladspa
      - --disable-libmms
      - --disable-librfb
      - --disable-libvisual
      - --disable-linsys
      - --disable-lv2
      - --disable-midi
      - --disable-mimic
      - --disable-modplug
      - --disable-mpeg2enc
      - --disable-mplex
      - --disable-musepack
      - --disable-mve
      - --disable-mxf
      - --disable-nas
      - --disable-neon
      - --disable-netsim
      - --disable-nuvdemux
      - --disable-nvenc
      - --disable-ofa
      - --disable-onvif
      - --disable-openal
      - --disable-opencv
      - --disable-openexr
      - --disable-openjpeg
      - --disable-openni2
      - --disable-opensles
      - --disable-opus
      - --disable-patchdetect
      - --disable-pcapparse
      - --disable-pnm
      - --disable-pvr
      - --disable-qt
      - --disable-removesilence
      - --disable-resindvd
      - --disable-rpath
      - --disable-rsvg
      - --disable-sbc
      - --disable-schro
      - --disable-sdi
      - --disable-sdp
      - --disable-shm
      - --disable-siren
      - --disable-sndfile
      - --disable-sndio
      - --disable-soundtouch
      - --disable-spandsp
      - --disable-spc
      - --disable-speed
      - --disable-srtp
      - --disable-stereo
      - --disable-subenc
      - --disable-teletextdec
      - --disable-timecode
      - --disable-timidity
      - --disable-tinyalsa
      - --disable-tta
      - --disable-uvch264
      - --disable-vcd
      - --disable-videofilters
      - --disable-videoframe_audiolevel
      - --disable-videomeasure
      - --disable-videosignal
      - --disable-vmnc
      - --disable-voaacenc
      - --disable-voamrwbenc
      - --disable-wasapi
      - --disable-webp
      - --disable-webrtcdsp
      - --disable-wildmidi
      - --disable-wininet
      - --disable-winks
      - --disable-winscreencap
      - --disable-y4m
      - --disable-yadif
      - --disable-zbar
    build-packages:
      - bison
      - flex
      - libasound2-dev
      - libgl1-mesa-dev
      - libgles2-mesa-dev
      - libneon27-gnutls-dev
      - liborc-0.4-dev
      - libpulse-dev
      - nettle-dev
    stage-packages:
      - libneon27-gnutls
      - libpulse0
    after:
      - gnome-platform
      - gst-plugins-base
      - gstreamer
      - libopenh264-library
    prime:
      - lib/libjson-c*
      - usr/lib/**/libneon*
      - usr/lib/gstreamer-1.0
      - -usr/lib/gstreamer-1.0/include
      - usr/lib/libgst*
      - usr/share/locale/**/gst-plugins-bad-*
    build-attributes: [no-system-libraries]

  corebird:
    plugin: autotools
    source: https://github.com/baedert/corebird/releases/download/1.6/corebird-1.6.tar.xz
    configflags:
      - --prefix=/snap/corebird/current/usr
      - --disable-rpath
      - --disable-spellcheck
    organize:
      snap/corebird/current/usr: usr
    build-packages:
      - libjson-glib-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - libxml2-utils
      - valac
    after:
      - desktop-gnome-platform
      - gnome-platform
      # - gst-plugins-bad
      # - gst-plugins-good
      - gst-plugins-libav
      - gstreamer
      # - gstreamer-vaapi
    prime:
      - usr/bin/corebird
      - usr/share/applications/org.baedert.corebird.desktop
      - usr/share/dbus-1/services/org.baedert.corebird.service
      - usr/share/glib-2.0/schemas/org.baedert.corebird.gschema.xml
      - usr/share/icons/**/corebird.png
      - usr/share/locale/**/corebird*
      - usr/share/metainfo/org.baedert.corebird.appdata.xml
    build-attributes: [no-system-libraries]
