name: cawbird

base: core18
grade: stable
confinement: strict

adopt-info: cawbird
summary: Cawbird Twitter Client (Corebird fork)
description: |
  Cawbird is a modern and lightweight Twitter client for the GNOME 3 desktop. It
  features inline image and video preview, creation of lists and favorites,
  filtering of tweets and full text search. Cawbird is able to manage multiple
  Twitter accounts.

  Cawbird is a fork of Corebird, which became unsupported after Twitter disabled
  the streaming API. Cawbird works with the new APIs and includes a few fixes
  and modifications that have historically been patched in to IBBoard's custom
  Corebird build on his personal Open Build Service account[1].

  Due to changes in the Twitter API[2], Cawbird has the following limitations:

  - Cawbird will update every two minutes
  - Cawbird does not get notified of the following, which will be refreshed on
    restart:
      - Unfavourite
      - Follow/Unfollow
      - Block/Unblock
      - Mute/Unmute
      - DM deletion
      - Some list changes

  All limitations are limitations imposed by Twitter and are not the fault of the
  Cawbird client.

  [1]: https://build.opensuse.org/project/show/home:IBBoard:desktop
  [2]: https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/introduction

slots:
  dbus-cawbird:
    interface: dbus
    bus: session
    name: uk.co.ibboard.cawbird

apps:
  cawbird:
    extensions: [gnome-3-28]
    command-chain:
    - snap/command-chain/alsa-launch
    - bin/libopenh264-launch
    command: bin/gstreamer-launch $SNAP/usr/bin/cawbird
    desktop: usr/share/applications/cawbird.desktop
    common-id: uk.co.ibboard.cawbird.desktop
    plugs:
    - audio-playback
    - desktop
    - desktop-legacy
    - gsettings
    - home
    - network
    - opengl
    - pulseaudio
    - unity7
    - wayland
    - x11

parts:
  alsa-mixin:
    plugin: nil
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    override-pull: |
      cat > asound.conf <<EOF
      pcm.!default {
          type pulse
          fallback "sysdefault"
          hint {
              show on
              description "Default ALSA Output (currently PulseAudio Sound Server)"
          }
      }
      ctl.!default {
          type pulse
          fallback "sysdefault"
      }
      EOF
      cat > alsa-launch <<EOF
      #!/bin/bash

      function append_dir() {
        local var="\$1"
        local dir="\$2"
        if [ -d "\$dir" ]; then
          eval "export \$var=\"\\\${\$var:+:\\\$\$var}\\\$dir\""
        fi
      }

      export ALSA_CONFIG_PATH="\$SNAP/etc/asound.conf"
      append_dir LD_LIBRARY_PATH "\$SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib"

      exec "\$@"
      EOF

      chmod +x alsa-launch
    override-build: |
      snapcraftctl build
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc asound.conf
      install -m755 -D -t $SNAPCRAFT_PART_INSTALL/snap/command-chain alsa-launch
    build-packages:
      - libasound2-dev

  libopenh264-helper:
    source: https://github.com/diddlesnaps/libopenh264-helper.git
    source-subdir: libopenh264
    plugin: make
    stage-packages:
    - bzip2
    - curl
    prime:
    - bin/bunzip2
    - bin/libopenh264-launch
    - usr/bin/curl
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasn1*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libcurl*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgssapi*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhcrypto*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libheim*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libhx509*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libkrb5*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/liblber*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libldap*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libnghttp*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpsl*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libroken*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/librtmp*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsasl*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libwind*

  libopenh264-library:
    after: [alsa-mixin]
    plugin: make
    source: https://github.com/cisco/openh264/archive/v1.7.0.tar.gz
    build-packages:
    - g++
    - gettext
    - libpulse-dev
    - nasm
    override-build: |
      snapcraftctl build
      find $SNAPCRAFT_PART_INSTALL/usr/local/lib/pkgconfig -name "*openh264*.pc" -exec \
        sed -i "s|/usr/local/include|$SNAPCRAFT_STAGE/usr/local/include|g;s|/usr/local/lib|$SNAPCRAFT_STAGE/usr/local/lib|g" '{}' \;
    prime:
    - usr/local/lib/libopenh264.so*

  gstreamer-helper:
    plugin: dump
    source: snap-files
    organize:
      gstreamer-launch: bin/gstreamer-launch

  gstreamer:
    after:
    - alsa-mixin
    - gnome-extension
    - libopenh264-library
    plugin: autotools
    source: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.16.1.tar.xz
    source-checksum: sha256/02211c3447c4daa55919c5c0f43a82a6fbb51740d57fc3af0639d46f1cf4377d
    configflags:
    - --prefix=/usr
    - --disable-benchmarks
    - --disable-debug
    - --disable-examples
    - --disable-gst-debug
    - --disable-gst-tracer-hooks
    - --disable-rpath
    - --disable-tests
    - --disable-tools
    build-packages:
    - bison
    - flex
    - gettext
    - liborc-0.4-dev
    - libpulse-dev
    - libxv-dev
    stage-packages:
    - libxv1
    override-build: |
      snapcraftctl build
      find $SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig -name "*gstreamer*.pc" -exec \
        sed -i "s|/usr/include|$SNAPCRAFT_STAGE/usr/include|g;s|/usr/lib|$SNAPCRAFT_STAGE/usr/lib|g" '{}' \;
    prime:
    - usr/lib/gstreamer-1.0/*.so
    - usr/lib/libgst*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libXv*
    - usr/libexec/gstreamer-1.0/gst-plugin-scanner

  gst-plugins-base:
    after:
    - alsa-mixin
    - gnome-extension
    - gstreamer
    plugin: autotools
    source: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.16.1.tar.xz
    source-checksum: sha256/5c3cc489933d0597087c9bc6ba251c93693d64554bcc563539a084fa2d5fcb2b
    configflags:
    - --prefix=/usr
    build-packages:
    - gettext
    - libfribidi-dev
    - libpulse-dev
    stage-packages:
    - libfribidi0
    override-build: |
      snapcraftctl build
      find $SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig -name "*gstreamer*.pc" -exec \
        sed -i "s|/usr/include|$SNAPCRAFT_STAGE/usr/include|g;s|/usr/lib|$SNAPCRAFT_STAGE/usr/lib|g" '{}' \;
    prime:
    - usr/lib/gstreamer-1.0/*.so
    - usr/lib/libgst*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libfribidi*

  gst-plugins-libav:
    after:
    - alsa-mixin
    - libopenh264-library
    - gnome-extension
    - gst-plugins-base
    plugin: autotools
    source: https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.16.1.tar.xz
    source-checksum: sha256/e8a5748ae9a4a7be9696512182ea9ffa6efe0be9b7976916548e9d4381ca61c4
    configflags:
    - --prefix=/usr
    - --enable-gpl
    - --enable-orc
    build-packages:
    - bison
    - flex
    - gettext
    - libgnutls28-dev
    - liborc-0.4-dev
    - libpulse-dev
    - libva-dev
    - libwayland-dev
    - libxrandr-dev
    - yasm
    - zlib1g-dev
    stage-packages:
    - libva-wayland2
    - libva-x11-2
    - libva2
    prime:
    - usr/lib/gstreamer-1.0/*.so
    - usr/lib/libgst*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libva*

  gst-plugins-good:
    after:
    - alsa-mixin
    - libopenh264-library
    - gnome-extension
    - gstreamer
    - gst-plugins-base
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.16.1.tar.xz
    source-checksum: sha256/9fbabe69018fcec707df0b71150168776040cde6c1a26bb5a82a136755fa8f1f
    configflags:
    - --prefix=/usr
    - --disable-aalib
    - --disable-aalibtest
    - --disable-alpha
    - --disable-apetag
    - --disable-audiofx
    - --disable-cutter
    - --disable-debug
    - --disable-debugutils
    - --disable-directsound
    - --disable-dtmf
    - --disable-dv1394
    - --disable-effectv
    - --disable-equalizer
    - --disable-examples
    - --disable-flac
    - --disable-flv
    - --disable-flx
    - --disable-goom
    - --disable-goom2k1
    - --disable-icydemux
    - --disable-id3demux
    - --disable-imagefreeze
    - --disable-interleave
    - --disable-jack
    - --disable-jpeg
    - --disable-law
    - --disable-level
    - --disable-libcaca
    - --disable-libdv
    - --disable-libpng
    - --disable-monoscope
    - --disable-oss
    - --disable-oss4
    - --disable-osx_audio
    - --disable-osx_video
    - --disable-replaygain
    - --disable-rpath
    - --disable-rtp
    - --disable-rtpmanager
    - --disable-rtsp
    - --disable-shapewipe
    - --disable-shout2
    - --disable-smpte
    - --disable-spectrum
    - --disable-speex
    - --disable-sunaudio
    - --disable-taglib
    - --disable-udp
    - --disable-videobox
    - --disable-vpx
    - --disable-waveform
    - --disable-wavenc
    - --disable-wavpack
    - --disable-wavparse
    - --disable-y4m
    build-packages:
    - bison
    - flex
    - gettext
    - liborc-0.4-dev
    - libpulse-dev
    prime:
    - usr/lib/gstreamer-1.0/*.so
    - usr/lib/libgst*

  gst-plugins-bad:
    after:
    - alsa-mixin
    - libopenh264-library
    - gnome-extension
    - gstreamer
    - gst-plugins-base
    plugin: autotools
    source: http://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.16.1.tar.xz
    source-checksum: sha256/56481c95339b8985af13bac19b18bc8da7118c2a7d9440ed70e7dcd799c2adb5
    configflags:
    - --prefix=/usr
    - --disable-accurip
    - --disable-acm
    - --disable-adpcmdec
    - --disable-adpcmenc
    - --disable-aiff
    - --disable-android_media
    - --disable-apexsink
    - --disable-apple_media
    - --disable-asfmux
    - --disable-assrender
    - --disable-audiofxbad
    - --disable-audiomixer
    - --disable-audiovisualizers
    - --disable-autoconvert
    - --disable-bayer
    - --disable-bluez
    - --disable-bs2b
    - --disable-bz2
    - --disable-camerabin2
    - --disable-cdxaparse
    - --disable-chromaprint
    - --disable-coloreffects
    - --disable-compositor
    - --disable-daala
    - --disable-dash
    - --disable-dc1394
    - --disable-dccp
    - --disable-debug
    - --disable-debugutils
    - --disable-decklink
    - --disable-direct3d
    - --disable-directfb
    - --disable-directsound
    - --disable-dtls
    - --disable-dvb
    - --disable-dvbsuboverlay
    - --disable-dvdspu
    - --disable-examples
    - --disable-faac
    - --disable-faceoverlay
    - --disable-fbdev
    - --disable-fdk_aac
    - --disable-festival
    - --disable-fieldanalysis
    - --disable-flite
    - --disable-fluidsynth
    - --disable-freeverb
    - --disable-frei0r
    - --disable-gaudieffects
    - --disable-gdp
    - --disable-geometrictransform
    - --disable-gme
    - --disable-gsm
    - --disable-hdvparse
    - --disable-id3tag
    - --disable-inter
    - --disable-interlace
    - --disable-ivfparse
    - --disable-ivtc
    - --disable-jp2kdecimator
    - --disable-jpegformat
    - --disable-kate
    - --disable-kms
    - --disable-ladspa
    - --disable-libmms
    - --disable-librfb
    - --disable-libvisual
    - --disable-linsys
    - --disable-lv2
    - --disable-midi
    - --disable-mimic
    - --disable-modplug
    - --disable-mpeg2enc
    - --disable-mplex
    - --disable-musepack
    - --disable-mve
    - --disable-mxf
    - --disable-nas
    - --disable-neon
    - --disable-netsim
    - --disable-nuvdemux
    - --disable-nvenc
    - --disable-ofa
    - --disable-onvif
    - --disable-openal
    - --disable-opencv
    - --disable-openexr
    - --disable-openjpeg
    - --disable-openni2
    - --disable-opensles
    - --disable-opus
    - --disable-patchdetect
    - --disable-pcapparse
    - --disable-pnm
    - --disable-pvr
    - --disable-qt
    - --disable-removesilence
    - --disable-resindvd
    - --disable-rpath
    - --disable-rsvg
    - --disable-sbc
    - --disable-schro
    - --disable-sdi
    - --disable-sdp
    - --disable-shm
    - --disable-siren
    - --disable-sndfile
    - --disable-sndio
    - --disable-soundtouch
    - --disable-spandsp
    - --disable-spc
    - --disable-speed
    - --disable-srtp
    - --disable-stereo
    - --disable-subenc
    - --disable-teletextdec
    - --disable-timecode
    - --disable-timidity
    - --disable-tinyalsa
    - --disable-tta
    - --disable-uvch264
    - --disable-vcd
    - --disable-videofilters
    - --disable-videoframe_audiolevel
    - --disable-videomeasure
    - --disable-videosignal
    - --disable-vmnc
    - --disable-voaacenc
    - --disable-voamrwbenc
    - --disable-wasapi
    - --disable-webp
    - --disable-webrtcdsp
    - --disable-wildmidi
    - --disable-wininet
    - --disable-winks
    - --disable-winscreencap
    - --disable-y4m
    - --disable-yadif
    - --disable-zbar
    build-packages:
    - bison
    - flex
    - gettext
    - libgl1-mesa-dev
    - libgles2-mesa-dev
    - libneon27-gnutls-dev
    - liborc-0.4-dev
    - libpulse-dev
    - nettle-dev
    stage-packages:
    - libneon27-gnutls
    override-build: |
      snapcraftctl build
      find $SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig -name "*gstreamer*.pc" -exec \
        sed -i "s|/usr/include|$SNAPCRAFT_STAGE/usr/include|g;s|/usr/lib|$SNAPCRAFT_STAGE/usr/lib|g" '{}' \;
    prime:
    - usr/lib/gstreamer-1.0/*.so
    - usr/lib/libgst*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libneon-gnutls*

  cawbird:
    after:
    - alsa-mixin
    - gnome-extension
    - gstreamer
    - gst-plugins-good
    - gst-plugins-bad
    - gst-plugins-libav
    # - gstreamer-vaapi
    parse-info: [usr/share/metainfo/uk.co.ibboard.cawbird.appdata.xml]
    plugin: meson
    source: https://github.com/ibboard/cawbird.git
    meson-parameters:
      - -Dprefix=/usr
    override-pull: |
      snapcraftctl pull

      git checkout "$(git describe --tags --abbrev=0 --match 'v*')"
      snapcraftctl set-version "$(git describe --tags | sed -e 's|^v||')"

      sed -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/scalable/apps/uk.co.ibboard.cawbird.svg|' data/uk.co.ibboard.cawbird.desktop.in
    build-packages:
    - gettext
    - libgspell-1-dev
    - libjson-glib-dev
    - libsoup2.4-dev
    - libsqlite3-dev
    - libxml2-utils
    - locales-all
    - valac
