name: corebird
version: "1.5"
grade: devel
summary: CoreBird Twitter Client
description: |
  Corebird is a modern and lightweight Twitter client for the GNOME 3 desktop. It
  features inline image and video preview, creation of lists and favorites,
  filtering of tweets and full text search. Corebird is able to manage multiple
  Twitter accounts.
confinement: strict
slots:
  dbus-corebird:
    interface: dbus
    bus: session
    name: org.baedert.corebird
apps:
  corebird:
    command: desktop-launch $SNAP/usr/bin/corebird
    #desktop: usr/share/applications/org.baedert.corebird.desktop
    plugs: [gsettings, home, network, opengl, pulseaudio, unity7, x11]
parts:
  desktop-helper:
    plugin: make
    source: desktop-helpers
    source-subdir: gtk
    make-parameters: ["FLAVOR=gtk3"]
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - shared-mime-info
      - locales-all

  openh264:
    plugin: make
    source: https://github.com/cisco/openh264/archive/v1.6.0.tar.gz
    build-packages:
      - nasm
    stage-packages:
      - bzip2
      - curl
    prime:
      - '-bin/bz*'
      - '-usr/local'
  
  corebird:
    plugin: jhbuild
    module-set: corebird.modules
    module-set-dir: .
    modules:
      - corebird
    # prepare: |
    #   # sed -i "s/revision=\"master\"/revision=\"$(git describe)\"/" corebird.modules
    #   sed -i "s/revision=\"master\"/revision=\"1.5\"/" corebird.modules
    build-packages:
      - bzip2
      - desktop-file-utils
      - doxygen
      - libcairo2-dev
      - libcurl4-openssl-dev
      - libdbus-1-dev
      - libegl1-mesa-dev
      - libenchant-dev
      - libepoxy-dev
      - libfaad-dev
      - libffi-dev
      - libfontconfig1-dev
      - libgl1-mesa-dev
      - libgnutls-dev
      - libgudev-1.0-dev
      - libharfbuzz-dev
      - libmount-dev
      - liborc-0.4-dev
      - libpng12-dev
      - libproxy-dev
      - libpulse-dev
      - libsqlite3-dev
      # - libtagc0-dev
      - libtiff5-dev
      - libunwind-dev
      - libv4l-dev
      # - libvpx-dev
      # - libwavpack-dev
      - libwayland-dev
      - libxcb-xkb-dev
      - libxft-dev
      - libxi-dev
      - libxml2-utils
      - libxslt1-dev
      - libxtst-dev
      - nasm
      - ragel
      - tar
      - wget
      - xmlto
      - xutils-dev
      - xz-utils
      - yasm
      - valac
    stage-packages:
      - bzip2
      - curl
      # - enchant
      # - gstreamer1.0-libav
      # - gstreamer1.0-plugins-bad
      # - gstreamer1.0-plugins-base
      # - gstreamer1.0-pulseaudio
      # - libcairo2
      # - libdbus-1-3
      # - libegl1-mesa
      # - libepoxy0
      # - libffi6
      # - libflac8
      - libfontconfig1
      # - libgnutls30
      # - libgudev-1.0-0
      # - libharfbuzz0b
      # - libmount1
      # - libpng12-0
      # - libproxy1v5
      # - libpulse0
      # - libsqlite3-0
      # - libtagc0
      # - libtiff5
      # - libunwind8
      # - libv4l-0
      # - libvpx3
      # - libwavpack1
      # - libwayland-client0
      # - libxcb-xkb1
      # - libxft2
      # - libxi6
      # - libxml2
      # - libxslt1.1
      # - libxtst6
    after: [desktop-helper, openh264]
    prime:
      - 'etc/fonts/'

      - 'lib/x86_64-linux-gnu/libexpat*'
      - 'lib/x86_64-linux-gnu/libpng*'

      - 'usr/bin/corebird'
      - 'usr/bin/gdk-pixbuf-query-loaders'
      - 'usr/bin/gio-querymodules'
      - 'usr/bin/gtk-query-immodules*'
      - 'usr/bin/update-mime-database*'

      - 'usr/lib/gdk-pixbuf-2.0/'
      - 'usr/lib/libgettextlib*'
      - 'usr/lib/gio/'
      - 'usr/lib/girepository-1.0/'
      - 'usr/lib/gstreamer-1.0/'
      - 'usr/lib/gtk-3.0/'
      - 'usr/lib/lib*'
      - 'usr/lib/locale/'

      - 'usr/lib/x86_64-linux-gnu/libasn1*'
      - 'usr/lib/x86_64-linux-gnu/libasyncns*'
      - 'usr/lib/x86_64-linux-gnu/libcairo*'
      - 'usr/lib/x86_64-linux-gnu/libcurl*'
      - 'usr/lib/x86_64-linux-gnu/libdrm*'
      - 'usr/lib/x86_64-linux-gnu/libenchant*'
      - 'usr/lib/x86_64-linux-gnu/libepoxy*'
      - 'usr/lib/x86_64-linux-gnu/libexpat*'
      - 'usr/lib/x86_64-linux-gnu/libfaad*'
      - 'usr/lib/x86_64-linux-gnu/libfontconfig*'
      - 'usr/lib/x86_64-linux-gnu/libfreetype*'
      - 'usr/lib/x86_64-linux-gnu/libglapi*'
      - 'usr/lib/x86_64-linux-gnu/libgnutls*'
      - 'usr/lib/x86_64-linux-gnu/libgssapi*'
      - 'usr/lib/x86_64-linux-gnu/libgudev*'
      - 'usr/lib/x86_64-linux-gnu/libhcrypto*'
      - 'usr/lib/x86_64-linux-gnu/libheimbase*'
      - 'usr/lib/x86_64-linux-gnu/libhogweed*'
      - 'usr/lib/x86_64-linux-gnu/libhx509*'
      - 'usr/lib/x86_64-linux-gnu/libicu*'
      - 'usr/lib/x86_64-linux-gnu/libidn*'
      - 'usr/lib/x86_64-linux-gnu/libjpeg*'
      - 'usr/lib/x86_64-linux-gnu/libnettle*'
      - 'usr/lib/x86_64-linux-gnu/liborc*'
      - 'usr/lib/x86_64-linux-gnu/libp11*'
      - 'usr/lib/x86_64-linux-gnu/libpng12*'
      - 'usr/lib/x86_64-linux-gnu/libproxy*'
      - 'usr/lib/x86_64-linux-gnu/libpulse*'
      - 'usr/lib/x86_64-linux-gnu/libroken*'
      - 'usr/lib/x86_64-linux-gnu/libsqlite3*'
      - 'usr/lib/x86_64-linux-gnu/libtasn1*'
      - 'usr/lib/x86_64-linux-gnu/libunwind*'
      - 'usr/lib/x86_64-linux-gnu/libv4l*'
      - 'usr/lib/x86_64-linux-gnu/libwind*'
      - 'usr/lib/x86_64-linux-gnu/libX11*'
      - 'usr/lib/x86_64-linux-gnu/libxcb*'
      - 'usr/lib/x86_64-linux-gnu/libXft*'
      - 'usr/lib/x86_64-linux-gnu/libXi*'
      - 'usr/lib/x86_64-linux-gnu/libxml*'
      - 'usr/lib/x86_64-linux-gnu/mesa*'

      - 'usr/share/appdata'
      - 'usr/share/applications/org.baedert.corebird.desktop'
      - 'usr/share/dbus-1/services/org.baedert.corebird.service'
      - 'usr/share/fonts/'
      - 'usr/share/icons/'
      - 'usr/share/locale/'
      - 'usr/share/wayland*'
      - 'usr/share/xml/iso-codes/'
